Polymer/pwa-starter-kit

- package-lock.json
- package.json
- src/components/my-view3.js
- Need to add more specificity (.checkout) to workaround an issue in lit-element: https://github.com/PolymerLabs/lit-element/issues/34
- up app-layout to pre.15
> style workaround

- src/components/my-app.js
I want to show my appreciation for this project with the `&hearts;` entity.
❤️
> Update heart emoticon in the footer

- gulpfile.js
- package.json
> Condense gulp build steps

- gulpfile.js
- package-lock.json
- package.json
@Dabolus you might be interested in this
> Rewrite gulpfile to follow gulp style

- index.html
> font fixes

- src/actions/app.js
- src/actions/shop.js
- src/reducers/app.js
- src/reducers/counter.js
- src/reducers/shop.js
I find that sentence without semicolons. Put semicolons that sentence without it.
> Put semicolons at files below src directory

- package-lock.json
- package.json
- src/components/my-app.js
- update to use lit-element#0.5.2 which has the [ShadyCSS fix](https://github.com/Polymer/lit-element/pull/102)
- use `role="main"` since `<main>` is not a thing in IE
> IE11 compatible 

- .gitignore
- README.md
and very very minor other changes
> Update readme with new docs link

- building-and-deploying.md
> Add App Engine Node.js Standard instructions

- css/main.css
Fixes #197 
(the selector should be "the first sibling" not "all siblings")
> fix sibling selector

- _config.yml
- _includes/analytics.html
- _layouts/default.html
- _layouts/post.html
- configuring-and-personalizing.md
- Add Google Analytics tracking code
- In `configuring-and-personalizing.md`
- `s/Configuring-and-personalizing/configuring-and-personalizing` in one of the links
- minor fixup in the file/folder structure diagram
- removed extra `</li>` in post.html
> Add Google Analytics tracking code

- _layouts/default.html
- _layouts/post.html
- css/main.css
Added a small site search:
(and did some minor css refactoring while i was in there)
> Add site: search

- README.md
https://github.com/Polymer/lit-element/commit/ff1e00ca2a2ab6d91970e5c88b4cd2d13f1b9252
> Remove fixed IE11 compatibility issues from readme

- package-lock.json
- package.json
- src/components/counter-element.js
- src/components/my-app.js
- src/components/my-view1.js
- src/components/my-view2.js
- src/components/my-view3.js
- src/components/my-view404.js
- src/components/page-view-element.js
- src/components/shop-cart.js
- src/components/shop-item.js
- src/components/shop-products.js
- src/components/snack-bar.js
- test/unit/counter-element.html
> Update to new lit-element API

- package-lock.json
- package.json
- src/actions/app.js
- src/actions/shop.js
- src/components/my-app.js
- src/components/shop-cart.js
- src/reducers/app.js
- src/reducers/counter.js
- src/reducers/shop.js
- src/store.js
Some small, non-breaking changes that will reduce the diff with the typescript branch.
>  Align master with TypeScript branch

- .gitignore
- _config.yml
- _layouts/default.html
- _layouts/post.html
- css/main.css
- css/theme.css
- images/alerts/info.svg
- images/alerts/warning.svg
- index.html
Preview at https://polymer-pwa-starter-kit.appspot.com/setup
> [docs] Style alert callouts

- index.html
- package-lock.json
- package.json
- push-manifest.json
- server/package-lock.json
- server/package.json
Fixes #254. Deployed to https://pwa-starter-kit.appspot.com/
> Add crossorigin=anonymous to push headers and update esm-amd-loader

- browser-support.md
- faq.md
Staged at https://20181213t124801-dot-polymer-pwa-starter-kit.appspot.com/faq
> Mention webpack branch; update browser support page

- src/components/snack-bar.js
> Don't show snack bar at startup

- package-lock.json
- package.json
- src/components/button-shared-styles.js
- src/components/counter-element.js
- src/components/my-app.js
- src/components/my-icons.js
- src/components/my-view1.js
- src/components/my-view2.js
- src/components/my-view3.js
- src/components/my-view404.js
- src/components/page-view-element.js
- src/components/shared-styles.js
- src/components/shop-cart.js
- src/components/shop-item.js
- src/components/shop-products.js
- src/components/snack-bar.js
Now using the new `static get styles()`.
> Update lit-element to v0.7.0

- src/components/counter-element.ts
- src/components/my-app.ts
- src/components/my-view1.ts
- src/components/my-view2.ts
- src/components/my-view3.ts
- src/components/my-view404.ts
- src/components/shop-cart.ts
- src/components/shop-item.ts
- src/components/shop-products.ts
- src/components/snack-bar.ts
- Use the customElement decorator to define class as a custom element
- Update static styles property
> [typescript branch] Add customElement decorator and update static styles property

- src/actions/shop.js
> Fix punctuation

- src/actions/shop.js
Fixed spelling error, also ESLint fixed some minor formatting.
> Spelling fix ISO #363

- package-lock.json
- package.json
The build process was not working. The reason relates to this issue:
https://github.com/Polymer/tools/issues/3389
that led to this change in the polymer CLI:
https://github.com/Polymer/tools/blob/master/packages/cli/CHANGELOG.md#v198-04-02-2019
Thanks!
> Upgrade polymer cli so build process works

- src/actions/shop.ts
> Update TypeScript template

- README.md
- index.html
- package-lock.json
- package.json
- server/.gcloudignore
- server/app.yaml
- src/actions/shop.js
Update Rollup branch
And then, update the deps: #368
> Update Rollup branch

- README.md
- package-lock.json
- package.json
- server/.gcloudignore
- server/app.yaml
- src/actions/shop.js
> Update no-cli branch

- README.md
- index.html
- package-lock.json
- package.json
- server/.gcloudignore
- server/app.yaml
- src/actions/shop.js
> Rollup update deps

- _layouts/default.html
Staged: https://20190925t123545-dot-polymer-pwa-starter-kit.appspot.com
> Update slack link

- README.md
> Update project status
