package.json
src/actions/app.js
src/components/my-app.js
src/components/my-view3.js
src/components/shop-cart.js
src/components/shop-products.js
src/reducers/app.js
src/reducers/shop.js

This PR moves some logic from the view layer into the store.
The goal is to make the separation between the data layer and the view layer a bit cleaner and make the view components easier to grok at a glance; for the most part, they only implement LitElement lifecycle methods and `stateChanged()`.

Light refactoring to move some logic from the view layer into the store

---

test/integration/visual.js

`height * height` is not an area 🤦‍♀️

math, how does it work

---

index.html

Fixes #89.
Unlike a regular `<script>`, by default [`<script type="module">` doesn't include credentials](https://jakearchibald.com/2017/es-modules-in-browsers/#no-credentials), so network requests for scripts will fail if they depend on credentials (e.g. the [Cloud Shell web preview service](https://cloud.google.com/shell/docs/features#web_preview)). This PR adds the `crossorigin` attribute to fix this, which won't be any different than transforming to AMD modules (on browsers without native ES modules) that use regular `<script>`s.

Add crossorigin to script type=module

---

package-lock.json
package.json

wct-browser-legacy 1.0.0 was pointing to v1 of webcomponentsjs.  This was causing two versions to install, incorrectly, into node_modules.

Updated package.json/package-lock.json to get latest wct-browser-legacy which uses `@webcomponents/webcomponentsjs` ^2.0.0

---

src/actions/app.js

Currently when a page is selected (e.g. clicking on the `View Two` tab), the app will try to import the page js (eg. my-view2.js) and wait for all the modules to be loaded and evaluated before setting the state `app.page` to `view2`.  This has a side effect of making the first render call of <my-view2> to be skipped since `app.page` hasn't updated yet right after the page is loaded and evaluated, and thus `_shouldRender` will return false. And only after `app.page` is updated to `view2` then `<my-view2>` will start to render its template, and that is the second render call.
I am proposing we should update the `app.page` state before the `import()`. This will fix https://github.com/Polymer/pwa-starter-kit/issues/93. It also has an advantage of making the UI feels more responsive as the tab …

change the order of import and updatePage

---

src/components/counter-element.js
src/components/my-view2.js

Changed the value property of `counter-element` in `my-view2.js` to reflect `props._value`.
It's the value that the end-user is likely to be interested in, and clicks are not usually relevant as a visual quantity.
The (+) and (-) buttons should produce a distinctly visible change to be more effective i.e. the (-) button should decrement something, and since the number of clicks cannot be decremented, it counter-intuitively seems to do nothing.
Removed repeated display of the value near the buttons, as it's unnecessarily confusing. It makes sense that the input area shows input-related data and the main display area shows the stored data, thereby also reinforcing the feeling that the data is being updated somewhere else, namely the redux store.
Changed the body text to reflect the changes. …

Minor changes to visual-semantics in layout and behavior of view2 following certain conventions

---

index.html

Moved preconnect hint higher in the head section in order to start the TLS handshake earlier
Added link rel preload hint to fetch and cache webcomponents-loader.js before it's needed by the browser
Minor grammar tweak

Performance tweaks

---

redux-and-state-management.md

A paren was missing in the console log statement in the section about Avoiding duplicate state.

[gh-pages] Missing paren in code example

---

index.html
test/unit/counter-element.html
test/unit/index.html
test/unit/views-a11y.html

Hey y’all!
I wanted to open a discussion on simplifying the viewport `<meta>` tag.
Two parts seem unnecessary: `user-scalable=yes` is the implicit default, and `minimum-scale=1` prevents zooming out for no good reason that I can think of.
This is how we’ve always done it in the good ol’ HTML5  Boilerplate:
```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```
What do you think?

Remove `minimum-scale=1,user-scalable=yes` from viewport <meta>

---

src/components/shop-products.js

Hey guys.
Not find import syntax for solve shop-item element on shop-products.js. 
The reason why it should be solved is because it imported by shop-cart.js.
I think shop-products.js need import syntax for solve shop-item element too.
Thank you

Add import syntax to import shop-item.js

---

package-lock.json
package.json

Since `redux-devtools-extension` has been updated on the Chrome Web Store and it is now compatible with Redux 4, it is now safe to update the Starter Kit dependency too. As already discussed in the issue, there are no changes needed to make the Starter Kit work with Redux 4. `redux-thunk` has been updated just for completeness, since its only change is the update of its TypeScript typings to Redux 4. The project has been tested on both Chrome `v67.0.3396.99` and Chrome Canary `v70.0.3501.0` with Redux DevTools `v2.15.3`, and everything kept working like a charm.
- [Redux v4 changelog](https://github.com/reduxjs/redux/releases/tag/v4.0.0)
- [Redux Thunk v2.3 changelog](https://github.com/reduxjs/redux-thunk/releases/tag/v2.3.0)
Fixes: https://github.com/Polymer/pwa-starter-kit/issues/76

Update Redux to v4 and Redux Thunk to v2.3

---

css/main.css

- Currently the search field is a bit too long on other browsers not Chrome. Fix by having a fixed width on input.
- On Safari, setting border: 0 is not enough, need to use -webkit-appearance trick.
- Make input bottom border aligned with the label

minor style update on the search field

---

src/components/my-view3.js

Remove workaround as the [issue](https://github.com/Polymer/lit-element/issues/34) has been fixed.

Remove workaround

---

configuring-and-personalizing.md
redux-and-state-management.md

Fixes https://github.com/Polymer/pwa-starter-kit/issues/229

Update doc to reflect LitElement changes

---

.gitignore

If not other files like `gulpfile.js`, `service-worker.js` and `sw-precache-config.js` will be ignored.

Ignore the .d.ts, .js & .js.map just in src folder

---

gulpfile.js
package.json

Opted to use gulp instead so we wouldn't need to install any more dev dependencies.
Fixes #244

Use gulp task to run `tsc --watch` and `polymer serve` in parallel

---

.travis.yml

Based on documentation seen in link below, the current supported versions are node 8 and 10. Travis uses version 9 for the moment, and should follow Polymer official support.
https://polymer-library.polymer-project.org/3.0/docs/tools/node-support

travis use node 10 as it is the latest supported version

---

package.json

(Opening this PR for consideration and discussion.)
Instead of having `npm run build` make both prpl-server and static builds, this will make prpl-server the default build and `npm run build:static` for the static build (and similarly for `serve`/`serve:static`). Having this default means users don't have to decide between `serve:prpl-server` and `serve:static` when first working with the project (which can be confusing).

Make prpl-server the default build/serve target

---

src/components/my-app.js

Since _locationChanged is not making use of ```location``` param probably it can be removed. What do you think?

Remove param from _locationChanged

---

index.html

Currently the starter kit has a meta tag `apple-mobile-web-app-status-bar-style` and it's set to `black-translucent`. The `black-translucent` setting makes the iOS status bar (when the app runs in full-screen mode) to have white text and the same background color as the body of the web app. Unfortunately the text color will remain white even if you use a light background color. This doesn't work well with pwa-starter-kit as it has a white background. We should change the setting to `default` (white background with black text).
After the change:

Change `apple-mobile-web-app-status-bar-style` to `default`

---

server/.gcloudignore
server/app.yaml

This makes App Engine Standard environment the default. This is fine for pwa-starter-kit and its current deployment, though note that current [Shop](https://github.com/Polymer/shop/blob/brotli/server/server.js) and [pwa-starter-kit-hn](https://github.com/Polymer/pwa-starter-kit-hn/blob/push-proxy/server/server.js) deployments still use Flexible environment so that the `shrink-ray-current` middleware for brotli compression works (and an instance is always up for maximum performance).
Fixes #322

Make App Engine Standard environment the default

---

building-and-deploying.md

Update doc to reflect the [changed default](https://github.com/Polymer/pwa-starter-kit/pull/323)

[docs] Make App Engine Standard environment the default

---

server/app.yaml

"secure: always" allows to redirect http to https with a redirect 302 (temporary).
Add "redirect_http_response_code: 301" allow to perform a redirect 301 (permanent).
See : https://cloud.google.com/appengine/docs/standard/nodejs/application-security#https_requests
See : https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#handlers_secure

Improve secure setting

---

README.md

This link results in page not found: https://pwa-starter-kit.polymer-project.org/setup/
This link results in how to get started page: https://pwa-starter-kit.polymer-project.org/setup

Fix broken link for "how to get started"

---

src/components/my-app.js

- Remove style not used on minimal-ui
Not related to this pull.
I created two branchs using typescript and minimal-ui template, i don't know if may be useful.
https://github.com/Arenari/pwa-starter-kit/tree/template-typescript-minimal-ui
https://github.com/Arenari/pwa-starter-kit/tree/typescript-minimal-ui-firebase

[minimal-ui] Remove style not used on minimal-ui
